language: ruby
sudo: false
cache:
  - bundler

rvm:
  - jruby-head
  - rbx-2
  - 1.9.3
  - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - ruby-head

addons:
  code_climate:
    repo_token: c3d9a5860bf10a8c3d8c620414a3dcc5875e6f47d7cabfe94b56d1043d71f37d

before_install:
  - gem install bundler

before_script:
  - bundle update

script:
  - bundle exec rake spec

matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-head
